# Generated by Django 3.0.2 on 2020-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
