# Generated by Django 2.2.1 on 2020-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0002_switch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouping_key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
