# Generated by Django 3.1.8 on 2022-02-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0004_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='aggregation',
            field=models.ForeignKey(blank=True, help_text='Aggregation virtual interface', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_members', to='switchinfo.interface'),
        ),
    ]
