# Generated by Django 5.2 on 2025-04-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0005_interface_aggregation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['name'], 'verbose_name_plural': 'switches'},
        ),
        migrations.AlterField(
            model_name='interface',
            name='aggregation',
            field=models.ForeignKey(blank=True, help_text='Aggregation virtual interface', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aggregation_members', to='switchinfo.interface'),
        ),
    ]
