# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_multilib:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6.11, 3.7, 3.8, 3.9 ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start snmpsim
      run: |
        docker pull tandrup/snmpsim
        docker run -d -v $(pwd)/test_data/snmp_data:/usr/local/snmpsim/data -p 161:161/udp tandrup/snmpsim
    - name: Install dependencies
      run: |
        sudo apt-get install libsnmp-dev libczmq-dev
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage parameterized easysnmp pyzmq netsnmp-py==0.5.2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        coverage run -p runtests.py tests.test_select_snmp
        coverage run -m tests.test_value_type
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}


  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
        snmp_library: [ 'netsnmp' ]
        include:
        - python-version: 3.6.11
          snmp_library: 'easysnmp'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start snmpsim
      run: |
        docker pull tandrup/snmpsim
        docker run -d -v $(pwd)/test_data/snmp_data:/usr/local/snmpsim/data -p 161:161/udp tandrup/snmpsim
    - name: Install dependencies
      run: |
        sudo apt-get install libsnmp-dev libczmq-dev
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage parameterized
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install netsnmp
      if: ${{matrix.snmp_library == 'netsnmp'}}
      run: |
        pip install -r optional-requirements-netsnmp.txt

    - name: Install easysnmp
      if: ${{matrix.snmp_library == 'easysnmp'}}
      run: |
        pip install -r optional-requirements-easysnmp.txt

    - name: Install pynetsnmp-2
      if: ${{matrix.snmp_library == 'pynetsnmp'}}
      run: pip install pynetsnmp-2

    - name: Run tests
      run: |
        coverage run -p runtests.py
        coverage run -p runtests_aruba.py
        coverage run -m tests.test_snmp
        coverage run -p runtests.py tests.load_info
        coverage run -m unittest discover tests_unittest
        coverage combine
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}

    - uses: codecov/codecov-action@v3
