# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]
        snmp_library: [ 'ezsnmp' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start snmpsim
      run: |
        docker pull tandrup/snmpsim
        docker run -d -v $(pwd)/test_data/snmp_data:/usr/local/snmpsim/data -p 161:161/udp tandrup/snmpsim
    - name: Install dependencies
      run: |
        sudo apt-get install libsnmp-dev libczmq-dev
        python -m pip install --upgrade pip poetry poetry-plugin-export
        python -m pip install flake8 coverage parameterized

    - name: Export requirements
      run: |
        poetry export -f requirements.txt --without-hashes --with snmp -o requirements.txt

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run tests with django
      run: |
        coverage run -p runtests.py tests.load_info
        coverage run -p runtests.py tests.test_snmp
        coverage run -p runtests.py tests.test_web
        coverage run -p runtests.py tests.tests_aruba
        coverage run -p runtests_aruba.py
        coverage run -m tests.test_snmp
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}

    - name: Run tests with unittest
      run: coverage run -m unittest discover tests_unittest
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}

    - name: Combine coverage
      run: coverage combine

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
