# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_multilib:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, 3.10, 3.11 ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start snmpsim
      run: |
        docker pull tandrup/snmpsim
        docker run -d -v $(pwd)/test_data/snmp_data:/usr/local/snmpsim/data -p 161:161/udp tandrup/snmpsim

    - name: Install dependencies
      run: |
        sudo apt-get install libsnmp-dev libczmq-dev
        python -m pip install --upgrade pip poetry poetry-plugin-export
        python -m pip install flake8 coverage parameterized
        poetry export -f requirements.txt --without-hashes --with netsnmp --with easysnmp -o requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      run: |
        coverage run -p runtests.py tests.test_select_snmp
        coverage run -m tests.test_value_type
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}

    - name: Combine coverage
      run: coverage combine

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}


  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, 3.10, 3.11 ]
        snmp_library: [ 'netsnmp', 'easysnmp' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start snmpsim
      run: |
        docker pull tandrup/snmpsim
        docker run -d -v $(pwd)/test_data/snmp_data:/usr/local/snmpsim/data -p 161:161/udp tandrup/snmpsim
    - name: Install dependencies
      run: |
        sudo apt-get install libsnmp-dev libczmq-dev
        python -m pip install --upgrade pip poetry poetry-plugin-export
        python -m pip install flake8 coverage parameterized

    - name: Export requirements for netsnmp
      if: ${{matrix.snmp_library == 'netsnmp'}}
      run: |
        poetry export -f requirements.txt --without-hashes --with netsnmp -o requirements.txt

    - name: Export requirements for easysnmp
      if: ${{matrix.snmp_library == 'easysnmp'}}
      run: |
        poetry export -f requirements.txt --without-hashes --with easysnmp -o requirements.txt

    - name: Install pynetsnmp-2
      if: ${{matrix.snmp_library == 'pynetsnmp'}}
      run: pip install pynetsnmp-2

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run tests with django
      run: |
        coverage run -p runtests.py tests.load_info
        coverage run -p runtests.py tests.test_snmp
        coverage run -p runtests.py tests.test_web
        coverage run -p runtests.py tests.tests_aruba
        coverage run -p runtests_aruba.py
        coverage run -m tests.test_snmp
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}

    - name: Run tests with unittest
      run: coverage run -m unittest discover tests_unittest
      env:
        SNMP_LIBRARY: ${{ matrix.snmp_library }}

    - name: Combine coverage
      run: coverage combine

    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
