# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        netsnmp: [ true ]
        include:
          - python-version: 3.6
            netsnmp: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start snmpsim
      run: |
        docker pull tandrup/snmpsim
        docker run -d -v $(pwd)/test_data/snmp_data:/usr/local/snmpsim/data -p 161:161/udp tandrup/snmpsim
    - name: Install dependencies
      run: |
        sudo apt-get install libsnmp-dev libczmq-dev
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install netsnmp
      if: ${{matrix.netsnmp == true}}
      run: |
        pip install -r optional-requirements-netsnmp.txt
    - name: Install easysnmp
      if: ${{matrix.netsnmp == false}}
      run: |
        pip install -r optional-requirements-easysnmp.txt

    - name: Run tests
      env:
        USE_NETSNMP: ${{ matrix.netsnmp }}
      run: |
        coverage run -p runtests.py
        coverage run -p runtests_aruba.py
        coverage run -p runtests_connect.py
        coverage run -m tests.test_snmp
        coverage combine
